scp *.ex4  hojre:/home/iman/Apps/MetaTrader4-1/MQL4/Experts
scp *.ex4  hojre:/home/iman/Apps/MetaTrader4-2/MQL4/Experts
scp *.ex4  hojre:/home/iman/Apps/MetaTrader4-3/MQL4/Experts
scp *.ex4  hojre:/home/iman/Apps/MetaTrader4-4/MQL4/Experts
scp *.ex4  hojre:/home/iman/Apps/MetaTrader4-5/MQL4/Experts
scp *.ex4  hojre:/home/iman/Apps/MetaTrader4-6/MQL4/Experts
scp *.ex4  hojre:/home/iman/Apps/MetaTrader4-7/MQL4/Experts
scp *.ex4  hojre:/home/iman/Apps/MetaTrader4-8/MQL4/Experts
scp *.ex4  hojre:/home/iman/Apps/MetaTrader4-9/MQL4/Experts
scp *.ex4  hojre:/home/iman/Apps/MetaTrader4-10/MQL4/Experts
scp *.ex4  hojre:/home/iman/Apps/MetaTrader4-11/MQL4/Experts
scp *.ex4  hojre:/home/iman/Apps/MetaTrader4-12/MQL4/Experts
scp *.ex4  hojre:/home/iman/Apps/MetaTrader4-13/MQL4/Experts
